# Cookie配置 (可选)
cookie: ''

cookies:
  msToken: NCVK_-kA158QB6N67ZQMB1fUI-8_F-_KiX6Ir-O_1sjfcdp5lfl38QUL7WIUWSwSZesBGujG-YZWL_DERSE9Z6VEk44yrepxxPipvbYlZ3PbQtKwIwNj5ed8s1bOEfH4l4DPLF6K2eQpTr4dEPghJuEYeF-3uphEryMb0n2rVJPTNKpGW1mdGDdb
  odin_tt: 3640a624d58ef7a1894a64c6c5dfd9e14005fb16d0c2abfc79b0b626e8a56c08c509c1c4edba0b4fcd8625d56e66810c2cb30a64937b98842580aee107148d3e
  passport_csrf_token: 1caa7161ad637f4621718e7f30b72c64
  sid_guard: 8981975001ea40abb5b02efbf5f2798d|1764958087|5184000|Tue,+03-Feb-2026+18:08:07+GMT
  ttwid: 1%7C-13S4EDkA7idkD0Db269lX5hzpXLG7uVAajtrKOlfYc|1765615848|c8a782a5a6621b2845de885ab4260a3b5dd1cda18808a3e11e0a94f97aeec03a
  
link:
- https://www.douyin.com/collection/7583170427477755938

path: G:\G Videos\[[抖音下載]]

# 下載執行程數
thread: 5

# 下載模式 (主頁鏈接時生效)
mode:
  - post

# 下載數量限制
number:
  post: 3      # 作品数量 (0表示全部)
  #like: 3      # 喜欢数量
  #music: 3     # 音乐数量
  #mix: 3       # 合集数量
  #allmix: 3    # 所有合集数量

increase:
  post: true
  like: false
  music: false
  mix: false
  allmix: false
  
# 下載內容設定
cover: true    # 下載封面
music: false    # 下載音樂
avatar: false   # 下載頭像
json: false     # 儲存JSON資料
folderstyle: false
database: true # 如果不使用數據庫, 增量更新將不可用

# 時間過濾
start_time: ''
end_time: ''

retry_times: 1



  

