link:
- https://www.douyin.com/user/MS4wLjABAAAA0d0eUrmvkM8u07ZvlThOg1E121OcRU_V6vqYBb-3L6myVZIgsU3lKP32jNrfPESS
path: ./Downloaded/
music: true
cover: true
avatar: false
json: true
start_time: ''
end_time: ''
mode:
- post
number:
  post: 2
  like: 0
thread: 5
retry_times: 3
cookies:
  msToken: ryKf3TmK8ybkOs_8BpmWjpWjYtN9HvN8LmoiZT5B1-KssS2Qg_gmzyn3NcH74rqsGedPulheDXxwbSLGoH4_kyXY6sRkc5dhD-rRU1UJWhqvBze70_kwKQ==
  passport_csrf_token: 95d58d74a91ebe7f8203172aff3dd0ce
  sessionid: cda798bccdf928cdb726f4d82e17496d
  sessionid_ss: cda798bccdf928cdb726f4d82e17496d
  ttwid: 1|ucuC8lFr0bgUwif1WKXA-2tktHlLEvcD0GnO5o_hPC0|1771375904|acfddb34246989b3a95428e9c15d936044b7aa40760497b03a3fff14f4f7b8b4
